TILE_SIZE = 50

GRID_HEIGHT = 14
GRID_WIDTH = 14

SCREEN_HEIGHT = GRID_HEIGHT * TILE_SIZE
SCREEN_WIDTH = GRID_WIDTH * TILE_SIZE

TEXT_BOX_BORDER_THICKNESS = 10

TEXT_BOX_POS = 1.2

LEFT_RIGHT_ENTRIES = [GRID_WIDTH // 2 - 1, GRID_WIDTH // 2, GRID_WIDTH // 2 + 1]
TOP_BOTTOM_ENTRIES = [GRID_HEIGHT // 2 - 1, GRID_HEIGHT // 2, GRID_HEIGHT // 2 + 1]
